/*
 * Copyright (C) 2012 Curtis Oakley
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.chockly.pm.gui;

import com.chockly.pm.games.CustomGame;
import com.chockly.pm.games.GameFactory;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author Curtis Oakley
 */
public class EditGame extends javax.swing.JDialog {

    /**
     * Creates a new EditGame form in add mode.
     * @param parent The dialogs parent frame.
     */
    public EditGame(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
        setTitle("New Custom Game");
    }
    
    /**
     * Creates a new EditGame form in edit mode.
     * @param parent The dialogs parent frame.
     * @param g The CustomGame to edit.
     */
    public EditGame(java.awt.Frame parent, CustomGame g){
        this(parent);
        
        setTitle("Edit " + g.getName());
        dirTxt.setText(g.getDir());
        exeTxt.setText(g.getExe());
        if(g.getIconPath() != null){
            iconTxt.setText(g.getIconPath());
            gameIcon.setIcon(g.getIcon());
        }
        nameTxt.setText(g.getName());
        profileTxt.setText(g.getSave());
        savesTxt.setText(g.getGameSaveDir());
        
        game = g;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        dirLabel = new javax.swing.JLabel();
        dirTxt = new javax.swing.JTextField();
        dirSelectBtn = new javax.swing.JButton();
        exeLabel = new javax.swing.JLabel();
        exeTxt = new javax.swing.JTextField();
        exeSelectBtn = new javax.swing.JButton();
        profileLabel = new javax.swing.JLabel();
        profileTxt = new javax.swing.JTextField();
        savesLabel = new javax.swing.JLabel();
        savesTxt = new javax.swing.JTextField();
        savesSelectBtn = new javax.swing.JButton();
        gameIcon = new javax.swing.JLabel();
        iconLabel = new javax.swing.JLabel();
        iconTxt = new javax.swing.JTextField();
        iconSelectBtn = new javax.swing.JButton();
        infoLabel = new javax.swing.JLabel();
        okBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        FormListener formListener = new FormListener();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        nameLabel.setText("Name:");

        nameTxt.setToolTipText("Name of the custom game");

        dirLabel.setText("Directory:");

        dirTxt.setToolTipText("Folder where the games save and profle folders are located.");

        dirSelectBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/chockly/pm/resources/blue-folder-search-result.png"))); // NOI18N
        dirSelectBtn.addActionListener(formListener);

        exeLabel.setText("Exe:");

        exeTxt.setToolTipText("Program to start when launching this game");

        exeSelectBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/chockly/pm/resources/blue-folder-search-result.png"))); // NOI18N
        exeSelectBtn.addActionListener(formListener);

        profileLabel.setText("Profile Folder:");

        profileTxt.setText("Profiles");
        profileTxt.setToolTipText("Name of the folder where to save the Profiles");

        savesLabel.setText("Saves Folder:");

        savesTxt.setText("Saves");
        savesTxt.setToolTipText("The name of the folder where the saved games are stored");

        savesSelectBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/chockly/pm/resources/blue-folder-search-result.png"))); // NOI18N
        savesSelectBtn.addActionListener(formListener);

        gameIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gameIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/chockly/pm/resources/game.png"))); // NOI18N
        gameIcon.setMaximumSize(new java.awt.Dimension(18, 18));
        gameIcon.setPreferredSize(new java.awt.Dimension(18, 18));

        iconLabel.setText("Icon:");

        iconTxt.setToolTipText("The location of the image to use as the icon for the game");

        iconSelectBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/chockly/pm/resources/blue-folder-search-result.png"))); // NOI18N
        iconSelectBtn.addActionListener(formListener);

        infoLabel.setForeground(requiredRed);

        okBtn.setText("Ok");
        okBtn.addActionListener(formListener);

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(formListener);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(exeLabel)
                            .addComponent(profileLabel)
                            .addComponent(dirLabel)
                            .addComponent(nameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dirTxt)
                                    .addComponent(exeTxt))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(exeSelectBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(dirSelectBtn, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nameTxt)
                                    .addComponent(profileTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(gameIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(iconLabel))
                            .addComponent(savesLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(savesTxt)
                            .addComponent(iconTxt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iconSelectBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(savesSelectBtn, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(infoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                        .addComponent(okBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dirLabel)
                        .addComponent(dirTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dirSelectBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(exeLabel)
                        .addComponent(exeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(exeSelectBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profileLabel)
                    .addComponent(profileTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(savesLabel)
                        .addComponent(savesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(savesSelectBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iconLabel)
                    .addComponent(iconTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gameIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iconSelectBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cancelBtn)
                        .addComponent(okBtn))
                    .addComponent(infoLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == dirSelectBtn) {
                EditGame.this.dirSelectBtnActionPerformed(evt);
            }
            else if (evt.getSource() == exeSelectBtn) {
                EditGame.this.exeSelectBtnActionPerformed(evt);
            }
            else if (evt.getSource() == savesSelectBtn) {
                EditGame.this.savesSelectBtnActionPerformed(evt);
            }
            else if (evt.getSource() == iconSelectBtn) {
                EditGame.this.iconSelectBtnActionPerformed(evt);
            }
            else if (evt.getSource() == cancelBtn) {
                EditGame.this.cancelBtnActionPerformed(evt);
            }
            else if (evt.getSource() == okBtn) {
                EditGame.this.okBtnActionPerformed(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    private void dirSelectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dirSelectBtnActionPerformed
        JFileChooser fc = new JFileChooser(new File(dirTxt.getText()));
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fc.setApproveButtonText("Set");
        
        int result = fc.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION)
            dirTxt.setText(fc.getSelectedFile().getAbsolutePath() + File.separator);
    }//GEN-LAST:event_dirSelectBtnActionPerformed

    private void exeSelectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exeSelectBtnActionPerformed
        JFileChooser fc = new JFileChooser(new File(exeTxt.getText()));
        fc.setFileFilter(new ExeFileFilter());
        fc.setAcceptAllFileFilterUsed(false);
        fc.setApproveButtonText("Set");
        
        int result = fc.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION)
            exeTxt.setText(fc.getSelectedFile().getAbsolutePath());
    }//GEN-LAST:event_exeSelectBtnActionPerformed

    private void savesSelectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savesSelectBtnActionPerformed
        JFileChooser fc = new JFileChooser(new File(savesTxt.getText()));
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fc.setApproveButtonText("Set");
        
        int result = fc.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION)
            savesTxt.setText(fc.getSelectedFile().getName());
    }//GEN-LAST:event_savesSelectBtnActionPerformed

    private void iconSelectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iconSelectBtnActionPerformed
        ImageFileChooser fc = new ImageFileChooser(iconTxt.getText());
        
        int result = fc.showOpenDialog(this);
        if (result == javax.swing.JFileChooser.APPROVE_OPTION) {
            iconTxt.setText(fc.getSelectedFile().getAbsolutePath());
            gameIcon.setIcon(new ImageIcon(iconTxt.getText()));
        }
    }//GEN-LAST:event_iconSelectBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        // Validate the fields
        String name = nameTxt.getText();
        String dir = dirTxt.getText();
        String exe = exeTxt.getText();
        String profileDir = profileTxt.getText();
        String saveDir = savesTxt.getText();

        boolean ready = true;

        if(name == null || name.isEmpty()){
            nameLabel.setForeground(requiredRed);
            ready = false;
        }
        if(dir == null || dir.isEmpty()){
            dirLabel.setForeground(requiredRed);
            ready = false;
        }
        if(exe == null || exe.isEmpty()){
            exeLabel.setForeground(requiredRed);
            ready = false;
        }
        if(profileDir == null || profileDir.isEmpty()){
            profileLabel.setForeground(requiredRed);
            ready = false;
        }
        if(saveDir == null || saveDir.isEmpty()){
            savesLabel.setForeground(requiredRed);
            ready = false;
        }
        
        if(ready){
            if(game == null){
                // Add a new Game
                GameFactory.addCustomGame(name,
                        dir,
                        exe,
                        iconTxt.getText(),
                        profileDir,
                        saveDir);
            } else {
                // Edit a game
                GameFactory.updateCustomGame(game,
                        nameTxt.getText(),
                        dirTxt.getText(),
                        exeTxt.getText(),
                        iconTxt.getText(),
                        profileTxt.getText(),
                        savesTxt.getText());
            }
            dispose();
        } else {
            infoLabel.setText("Please fill out all required fields.");
        }
    }//GEN-LAST:event_okBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel dirLabel;
    private javax.swing.JButton dirSelectBtn;
    private javax.swing.JTextField dirTxt;
    private javax.swing.JLabel exeLabel;
    private javax.swing.JButton exeSelectBtn;
    private javax.swing.JTextField exeTxt;
    private javax.swing.JLabel gameIcon;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JButton iconSelectBtn;
    private javax.swing.JTextField iconTxt;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JButton okBtn;
    private javax.swing.JLabel profileLabel;
    private javax.swing.JTextField profileTxt;
    private javax.swing.JLabel savesLabel;
    private javax.swing.JButton savesSelectBtn;
    private javax.swing.JTextField savesTxt;
    // End of variables declaration//GEN-END:variables

    private CustomGame game = null;
    private java.awt.Color requiredRed = new java.awt.Color(204, 0, 0);
}
